name: balance_meal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  uuid: ^4.0.0
  fl_chart: ^0.65.0
  freezed_annotation: ^2.4.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  go_router: ^12.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  percent_indicator: ^4.2.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

